// Definisi setiap tool: field-field opsi dipetakan langsung menjadi
// payload JSON yang dikirim backend ke API pemrosesan PDF (lihat nama-nama
// opsi pada dokumentasi API pemrosesan PDF yang dipakai backend).
//
// tipe field yang didukung ToolView.vue: text, number, select, checkbox, color, textarea

export const TOOLS = [
  {
    key: "merge",
    label: "Gabung PDF",
    description: "Gabungkan beberapa file PDF menjadi satu file.",
    icon: "🧩",
    inputType: "file",
    multiple: true,
    accept: ".pdf",
    fields: [],
  },
  {
    key: "split",
    label: "Pisah PDF",
    description: "Pisahkan PDF berdasarkan rentang halaman atau ukuran file.",
    icon: "✂️",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    fields: [
      {
        name: "split_mode",
        label: "Mode pemisahan",
        type: "select",
        default: "ranges",
        options: ["ranges", "fixed_range", "remove_pages"],
      },
      {
        name: "ranges",
        label: "Rentang halaman (mis. 1-3,5-7)",
        type: "text",
        default: "",
        showIf: { field: "split_mode", equals: "ranges" },
      },
      {
        name: "fixed_range",
        label: "Jumlah halaman per file",
        type: "number",
        default: 1,
        showIf: { field: "split_mode", equals: "fixed_range" },
      },
      {
        name: "remove_pages",
        label: "Halaman yang dihapus (mis. 2,4-6)",
        type: "text",
        default: "",
        showIf: { field: "split_mode", equals: "remove_pages" },
      },
      { name: "merge_after", label: "Gabung ulang hasil jadi satu file", type: "checkbox", default: false },
    ],
  },
  {
    key: "splitsmart",
    label: "Pisah PDF (Smart/AI)",
    description: "Biarkan AI menentukan bagian dokumen berdasarkan instruksi kamu.",
    icon: "🤖",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    fields: [
      {
        name: "prompt",
        label: "Instruksi pemisahan",
        type: "textarea",
        default: "",
        placeholder: "Contoh: pisahkan setiap bab menjadi file terpisah",
        required: true,
      },
    ],
  },
  {
    key: "compress",
    label: "Kompres PDF",
    description: "Perkecil ukuran file PDF.",
    icon: "🗜️",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    fields: [
      {
        name: "compression_level",
        label: "Level kompresi",
        type: "select",
        default: "recommended",
        options: ["low", "recommended", "extreme"],
      },
    ],
  },
  {
    key: "rotate",
    label: "Putar PDF",
    description: "Putar halaman PDF. Sudut yang sama diterapkan ke semua file yang diunggah.",
    icon: "🔄",
    inputType: "file",
    multiple: true,
    accept: ".pdf",
    fields: [
      {
        name: "rotate",
        label: "Sudut putar",
        type: "select",
        default: "90",
        options: ["0", "90", "180", "270"],
        cast: "number",
      },
    ],
  },
  {
    key: "watermark",
    label: "Beri Watermark",
    description: "Tambahkan watermark teks ke seluruh halaman PDF.",
    icon: "💧",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    fields: [
      { name: "text", label: "Teks watermark", type: "text", default: "CONFIDENTIAL", required: true },
      { name: "pages", label: "Halaman (mis. all / 1-3)", type: "text", default: "all" },
      {
        name: "vertical_position",
        label: "Posisi vertikal",
        type: "select",
        default: "middle",
        options: ["top", "middle", "bottom"],
      },
      {
        name: "horizontal_position",
        label: "Posisi horizontal",
        type: "select",
        default: "center",
        options: ["left", "center", "right"],
      },
      { name: "font_size", label: "Ukuran font", type: "number", default: 34, cast: "number" },
      { name: "font_color", label: "Warna font", type: "color", default: "#000000" },
      { name: "rotation", label: "Rotasi (derajat)", type: "number", default: 45, cast: "number" },
      { name: "transparency", label: "Transparansi (%)", type: "number", default: 60, cast: "number" },
      { name: "mosaic", label: "Ulangi sebagai mosaik", type: "checkbox", default: false },
    ],
  },
  {
    key: "pagenumber",
    label: "Nomor Halaman",
    description: "Tambahkan nomor halaman otomatis ke PDF.",
    icon: "🔢",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    fields: [
      {
        name: "position",
        label: "Posisi",
        type: "select",
        default: "bottom_center",
        options: [
          "top_left", "top_center", "top_right",
          "bottom_left", "bottom_center", "bottom_right",
        ],
      },
      { name: "format", label: "Format (mis. {page_number}/{total_pages})", type: "text", default: "{page_number}" },
      { name: "start_number", label: "Mulai dari nomor", type: "number", default: 1, cast: "number" },
      { name: "font_size", label: "Ukuran font", type: "number", default: 12, cast: "number" },
      { name: "font_color", label: "Warna font", type: "color", default: "#000000" },
      { name: "pages", label: "Halaman (mis. all / 2-10)", type: "text", default: "all" },
      { name: "show_on_cover", label: "Tampilkan di halaman sampul", type: "checkbox", default: false },
    ],
  },
  {
    key: "unlock",
    label: "Buka Kunci PDF",
    description: "Hapus password dari PDF yang terkunci (perlu password saat ini).",
    icon: "🔓",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    fields: [
      { name: "password", label: "Password saat ini", type: "text", default: "", required: true },
    ],
  },
  {
    key: "protect",
    label: "Kunci PDF (Password)",
    description: "Tambahkan password ke PDF.",
    icon: "🔒",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    fields: [
      { name: "password", label: "Password baru", type: "text", default: "", required: true },
    ],
  },
  {
    key: "repair",
    label: "Perbaiki PDF",
    description: "Perbaiki file PDF yang rusak atau tidak bisa dibuka.",
    icon: "🛠️",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    fields: [],
  },
  {
    key: "pdfjpg",
    label: "PDF ke JPG",
    description: "Ubah setiap halaman PDF menjadi gambar JPG, atau ekstrak gambar di dalamnya.",
    icon: "🖼️",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    fields: [
      {
        name: "pdfjpg_mode",
        label: "Mode",
        type: "select",
        default: "pages",
        options: ["pages", "extract"],
      },
    ],
  },
  {
    key: "imagepdf",
    label: "Gambar ke PDF",
    description: "Gabungkan satu atau beberapa gambar menjadi file PDF.",
    icon: "📷",
    inputType: "file",
    multiple: true,
    accept: ".jpg,.jpeg,.png,.gif,.bmp,.tiff,.tif,.webp",
    fields: [
      {
        name: "orientation",
        label: "Orientasi halaman",
        type: "select",
        default: "portrait",
        options: ["portrait", "landscape"],
      },
      {
        name: "pagesize",
        label: "Ukuran halaman",
        type: "select",
        default: "fit",
        options: ["fit", "A4", "letter"],
      },
      { name: "margin", label: "Margin (px)", type: "number", default: 0, cast: "number" },
      { name: "merge_after", label: "Gabung semua gambar jadi satu PDF", type: "checkbox", default: true },
    ],
  },
  {
    key: "officepdf",
    label: "Office ke PDF",
    description: "Konversi Word, Excel, atau PowerPoint menjadi PDF.",
    icon: "📄",
    inputType: "file",
    multiple: false,
    accept: ".doc,.docx,.xls,.xlsx,.ppt,.pptx,.odt,.ods,.odp,.rtf,.txt",
    fields: [],
  },
  {
    key: "htmlpdf",
    label: "Website (HTML) ke PDF",
    description: "Ubah sebuah halaman web menjadi file PDF.",
    icon: "🌐",
    inputType: "url",
    multiple: false,
    fields: [
      {
        name: "page_orientation",
        label: "Orientasi",
        type: "select",
        default: "portrait",
        options: ["portrait", "landscape"],
      },
      {
        name: "page_size",
        label: "Ukuran halaman",
        type: "select",
        default: "A4",
        options: ["A4", "letter", "legal"],
      },
      { name: "single_page", label: "Jadikan satu halaman panjang", type: "checkbox", default: false },
    ],
  },
  {
    key: "pdfa",
    label: "Konversi ke PDF/A",
    description: "Konversi PDF ke format arsip standar PDF/A.",
    icon: "🗄️",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    fields: [
      {
        name: "conformance",
        label: "Level konformansi",
        type: "select",
        default: "pdfa-2b",
        options: ["pdfa-1b", "pdfa-2b", "pdfa-3b"],
      },
      { name: "allow_downgrade", label: "Izinkan downgrade level jika perlu", type: "checkbox", default: true },
    ],
  },
  {
    key: "validatepdfa",
    label: "Validasi PDF/A",
    description: "Periksa apakah file PDF sudah memenuhi standar PDF/A.",
    icon: "✅",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    resultKind: "auto",
    fields: [
      {
        name: "conformance",
        label: "Level konformansi",
        type: "select",
        default: "pdfa-2b",
        options: ["pdfa-1b", "pdfa-2b", "pdfa-3b"],
      },
    ],
  },
  {
    key: "pdfocr",
    label: "OCR PDF (Bisa dicari)",
    description: "Jadikan PDF hasil scan bisa dicari teksnya (OCR).",
    icon: "🔍",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    fields: [
      { name: "ocr_languages", label: "Bahasa OCR (kode, mis. eng, ind)", type: "text", default: "eng" },
    ],
  },
  {
    key: "extract",
    label: "Ekstrak Teks PDF",
    description: "Ambil semua teks dari dalam file PDF.",
    icon: "📋",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    resultKind: "auto",
    fields: [
      { name: "detailed", label: "Sertakan detail posisi & font tiap teks", type: "checkbox", default: false },
    ],
  },
  {
    key: "pdfmarkdown",
    label: "PDF ke Markdown",
    description: "Konversi isi PDF menjadi teks format Markdown.",
    icon: "📝",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    fields: [],
  },
  {
    key: "translate",
    label: "Terjemahkan PDF",
    description: "Terjemahkan isi PDF ke bahasa lain.",
    icon: "🌍",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    fields: [
      { name: "language_input", label: "Bahasa asal (kode, mis. en)", type: "text", default: "en", required: true },
      { name: "language_output", label: "Bahasa tujuan (kode, mis. id)", type: "text", default: "id", required: true },
    ],
  },
  {
    key: "summarize",
    label: "Ringkas PDF",
    description: "Buat ringkasan otomatis dari isi PDF.",
    icon: "📑",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    fields: [
      { name: "language", label: "Bahasa ringkasan (kode, mis. id)", type: "text", default: "id" },
      {
        name: "output_format",
        label: "Format hasil",
        type: "select",
        default: "pdf",
        options: ["pdf", "txt"],
      },
    ],
  },
  {
    key: "formsdetect",
    label: "Deteksi Form PDF",
    description: "Deteksi field formulir yang ada di dalam PDF.",
    icon: "🧾",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    resultKind: "auto",
    fields: [],
  },
  {
    key: "editpdf",
    label: "Edit PDF (lanjutan)",
    description: "Tambahkan elemen (teks/gambar) ke PDF lewat data JSON mentah sesuai dokumentasi API pemrosesan PDF.",
    icon: "✍️",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    advanced: true,
    fields: [
      {
        name: "elements",
        label: "elements (JSON array, lihat dokumentasi API)",
        type: "textarea",
        default: "[]",
        json: true,
      },
    ],
  },
  {
    key: "sign",
    label: "Tanda Tangan PDF (lanjutan)",
    description: "Kirim permintaan tanda tangan lewat data JSON mentah sesuai dokumentasi API pemrosesan PDF.",
    icon: "🖊️",
    inputType: "file",
    multiple: false,
    accept: ".pdf",
    advanced: true,
    resultKind: "auto",
    fields: [
      {
        name: "signers",
        label: "signers (JSON array, lihat dokumentasi API)",
        type: "textarea",
        default: "[]",
        json: true,
      },
    ],
  },
];

export function getToolConfig(key) {
  return TOOLS.find((t) => t.key === key);
}
